apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs-dev
  namespace: default
spec:
  chart: nfs-subdir-external-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  targetNamespace: default
  set:
    nfs.server: 127.0.0.1
    nfs.path: /nfs
    storageClass.name: nfs-dev
